// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

// APIProductVersionSpec - API product version specification
type APIProductVersionSpec struct {
	// The contents of the API product version specification
	Content string `json:"content"`
	// An ISO-8601 timestamp representation of entity creation date.
	CreatedAt time.Time `json:"created_at"`
	// The API product version specification identifier.
	ID string `json:"id"`
	// The name of the API product version specification
	Name string `json:"name"`
	// An ISO-8601 timestamp representation of entity update date.
	UpdatedAt time.Time `json:"updated_at"`
}
