// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

type APIProduct struct {
	// An ISO-8601 timestamp representation of entity creation date.
	CreatedAt time.Time `json:"created_at"`
	// The description of the API product
	Description *string `json:"description"`
	// The API product ID.
	ID string `json:"id"`
	// description: A maximum of 5 user-defined labels are allowed on this resource.
	// Keys must not start with kong, konnect, insomnia, mesh, kic or _, which are reserved for Kong.
	// Keys are case-sensitive.
	//
	Labels map[string]string `json:"labels"`
	// The name of the API product
	Name string `json:"name"`
	// The list of portal identifiers which this API product is published to
	PortalIds []string `json:"portal_ids"`
	// An ISO-8601 timestamp representation of entity update date.
	UpdatedAt time.Time `json:"updated_at"`
}
