// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type BreakBlock struct {
	// List of children nodes of the current node
	Children []AnyNode `json:"children,omitempty"`
	Type     string    `json:"type"`
}
