// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type HeadingBlock struct {
	// List of children nodes of the current node
	Children []AnyNode `json:"children,omitempty"`
	// Level of the heading which maps to HTML <h> tag
	Level *float64 `json:"level,omitempty"`
	Type  string   `json:"type"`
}
