// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type IDPClaimMappings struct {
	Email  *string `json:"email,omitempty"`
	Groups *string `json:"groups,omitempty"`
	Name   *string `json:"name,omitempty"`
}

// IDP - The IdP object contains the configuration data for the OIDC authentication integration.
//
// NOTE: The `openid` scope is required. Removing it could break the OIDC integration.
type IDP struct {
	ClaimMappings *IDPClaimMappings `json:"claim_mappings,omitempty"`
	ClientID      *string           `json:"client_id,omitempty"`
	Issuer        *string           `json:"issuer,omitempty"`
	LoginPath     *string           `json:"login_path,omitempty"`
	Scopes        []string          `json:"scopes,omitempty"`
}
