// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Link struct {
	// Target url of the link
	Href *string `json:"href,omitempty"`
	// Title of the link
	Title *string `json:"title,omitempty"`
	Type  string  `json:"type"`
}
