// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// LogLevel - Log levels are set in Kong’s configuration. Log levels increase in order of their severity
type LogLevel string

const (
	LogLevelInfo   LogLevel = "info"
	LogLevelNotice LogLevel = "notice"
	LogLevelWarn   LogLevel = "warn"
	LogLevelError  LogLevel = "error"
	LogLevelCrit   LogLevel = "crit"
)

func (e LogLevel) ToPointer() *LogLevel {
	return &e
}

func (e *LogLevel) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "info":
		fallthrough
	case "notice":
		fallthrough
	case "warn":
		fallthrough
	case "error":
		fallthrough
	case "crit":
		*e = LogLevel(v)
		return nil
	default:
		return fmt.Errorf("invalid value for LogLevel: %v", v)
	}
}
