// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Security struct {
	KonnectAccessToken       *string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
	PersonalAccessToken      *string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
	SystemAccountAccessToken *string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}
