// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type TaskCheckbox struct {
	// State of the checkbox
	Checked bool   `json:"checked"`
	Type    string `json:"type"`
}
