// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// TeamMapping - A team assignment is a mapping of an IdP group to a Konnect Team.
type TeamMapping struct {
	// The IdP group.
	Group *string `json:"group,omitempty"`
	// An array of ID's that are mapped to the specified group.
	TeamIds []string `json:"team_ids,omitempty"`
}
