// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// UnauthorizedError - standard error
type UnauthorizedError struct {
	Detail   interface{} `json:"detail"`
	Instance interface{} `json:"instance"`
	Status   interface{} `json:"status"`
	Title    interface{} `json:"title"`
	Type     interface{} `json:"type,omitempty"`
}

func (o *UnauthorizedError) GetDetail() interface{} {
	if o == nil {
		return nil
	}
	return o.Detail
}

func (o *UnauthorizedError) GetInstance() interface{} {
	if o == nil {
		return nil
	}
	return o.Instance
}

func (o *UnauthorizedError) GetStatus() interface{} {
	if o == nil {
		return nil
	}
	return o.Status
}

func (o *UnauthorizedError) GetTitle() interface{} {
	if o == nil {
		return nil
	}
	return o.Title
}

func (o *UnauthorizedError) GetType() interface{} {
	if o == nil {
		return nil
	}
	return o.Type
}
