// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// UnsupportedMediaTypeError - standard error
type UnsupportedMediaTypeError struct {
	Detail   interface{} `json:"detail"`
	Instance interface{} `json:"instance"`
	Status   interface{} `json:"status"`
	Title    interface{} `json:"title"`
	Type     interface{} `json:"type,omitempty"`
}

func (o *UnsupportedMediaTypeError) GetDetail() interface{} {
	if o == nil {
		return nil
	}
	return o.Detail
}

func (o *UnsupportedMediaTypeError) GetInstance() interface{} {
	if o == nil {
		return nil
	}
	return o.Instance
}

func (o *UnsupportedMediaTypeError) GetStatus() interface{} {
	if o == nil {
		return nil
	}
	return o.Status
}

func (o *UnsupportedMediaTypeError) GetTitle() interface{} {
	if o == nil {
		return nil
	}
	return o.Title
}

func (o *UnsupportedMediaTypeError) GetType() interface{} {
	if o == nil {
		return nil
	}
	return o.Type
}
