// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/kong/terraform-provider-konnect/internal/sdk"
	"github.com/kong/terraform-provider-konnect/internal/sdk/pkg/models/operations"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ datasource.DataSource = &ServiceDataSource{}
var _ datasource.DataSourceWithConfigure = &ServiceDataSource{}

func NewServiceDataSource() datasource.DataSource {
	return &ServiceDataSource{}
}

// ServiceDataSource is the data source implementation.
type ServiceDataSource struct {
	client *sdk.Konnect
}

// ServiceDataSourceModel describes the data model.
type ServiceDataSourceModel struct {
	ConnectTimeout types.Int64  `tfsdk:"connect_timeout"`
	ControlPlaneID types.String `tfsdk:"control_plane_id"`
	CreatedAt      types.Int64  `tfsdk:"created_at"`
	Enabled        types.Bool   `tfsdk:"enabled"`
	FilterTags     types.String `tfsdk:"filter_tags"`
	Host           types.String `tfsdk:"host"`
	ID             types.String `tfsdk:"id"`
	Name           types.String `tfsdk:"name"`
	Offset         types.String `tfsdk:"offset"`
	Path           types.String `tfsdk:"path"`
	Port           types.Int64  `tfsdk:"port"`
	Protocol       types.String `tfsdk:"protocol"`
	ReadTimeout    types.Int64  `tfsdk:"read_timeout"`
	Retries        types.Int64  `tfsdk:"retries"`
	Size           types.Int64  `tfsdk:"size"`
	UpdatedAt      types.Int64  `tfsdk:"updated_at"`
	WriteTimeout   types.Int64  `tfsdk:"write_timeout"`
}

// Metadata returns the data source type name.
func (r *ServiceDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_service"
}

// Schema defines the schema for the data source.
func (r *ServiceDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Service DataSource",

		Attributes: map[string]schema.Attribute{
			"connect_timeout": schema.Int64Attribute{
				Computed: true,
			},
			"control_plane_id": schema.StringAttribute{
				Required:    true,
				Description: `The UUID of your control plane. This variable is available in the Konnect manager`,
			},
			"created_at": schema.Int64Attribute{
				Computed:    true,
				Description: `Unix epoch when the resource was last created.`,
			},
			"enabled": schema.BoolAttribute{
				Computed:    true,
				Description: `Service enabled boolean`,
			},
			"filter_tags": schema.StringAttribute{
				Optional:    true,
				Description: `A list of tags to filter the list of resources on. Multiple tags can be concatenated using ',' to mean AND or using '/' to mean OR.`,
			},
			"host": schema.StringAttribute{
				Computed: true,
			},
			"id": schema.StringAttribute{
				Required:    true,
				Description: `UUID of the service to lookup`,
			},
			"name": schema.StringAttribute{
				Computed: true,
			},
			"offset": schema.StringAttribute{
				Optional:    true,
				Description: `Offset from which to return the next set of resources. Use the value of the 'offset' field from the response of a list operation as input here to paginate through all the resources`,
			},
			"path": schema.StringAttribute{
				Computed: true,
			},
			"port": schema.Int64Attribute{
				Computed: true,
			},
			"protocol": schema.StringAttribute{
				Computed: true,
			},
			"read_timeout": schema.Int64Attribute{
				Computed: true,
			},
			"retries": schema.Int64Attribute{
				Computed: true,
			},
			"size": schema.Int64Attribute{
				Optional:    true,
				Description: `Number of resources to be returned. Default: 100`,
			},
			"updated_at": schema.Int64Attribute{
				Computed: true,
			},
			"write_timeout": schema.Int64Attribute{
				Computed: true,
			},
		},
	}
}

func (r *ServiceDataSource) Configure(ctx context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	// Prevent panic if the provider has not been configured.
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*sdk.Konnect)

	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected DataSource Configure Type",
			fmt.Sprintf("Expected *sdk.Konnect, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)

		return
	}

	r.client = client
}

func (r *ServiceDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data *ServiceDataSourceModel
	var item types.Object

	resp.Diagnostics.Append(req.Config.Get(ctx, &item)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(item.As(ctx, &data, basetypes.ObjectAsOptions{
		UnhandledNullAsEmpty:    true,
		UnhandledUnknownAsEmpty: true,
	})...)

	if resp.Diagnostics.HasError() {
		return
	}

	controlPlaneID := data.ControlPlaneID.ValueString()
	filterTags := new(string)
	if !data.FilterTags.IsUnknown() && !data.FilterTags.IsNull() {
		*filterTags = data.FilterTags.ValueString()
	} else {
		filterTags = nil
	}
	offset := new(string)
	if !data.Offset.IsUnknown() && !data.Offset.IsNull() {
		*offset = data.Offset.ValueString()
	} else {
		offset = nil
	}
	serviceID := data.ID.ValueString()
	size := new(int64)
	if !data.Size.IsUnknown() && !data.Size.IsNull() {
		*size = data.Size.ValueInt64()
	} else {
		size = nil
	}
	request := operations.GetServiceRequest{
		ControlPlaneID: controlPlaneID,
		FilterTags:     filterTags,
		Offset:         offset,
		ServiceID:      serviceID,
		Size:           size,
	}
	res, err := r.client.Services.GetService(ctx, request)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		if res != nil && res.RawResponse != nil {
			resp.Diagnostics.AddError("unexpected http request/response", debugResponse(res.RawResponse))
		}
		return
	}
	if res == nil {
		resp.Diagnostics.AddError("unexpected response from API", fmt.Sprintf("%v", res))
		return
	}
	if res.StatusCode != 200 {
		resp.Diagnostics.AddError(fmt.Sprintf("unexpected response from API. Got an unexpected response code %v", res.StatusCode), debugResponse(res.RawResponse))
		return
	}
	if res.Object == nil {
		resp.Diagnostics.AddError("unexpected response from API. No response body", debugResponse(res.RawResponse))
		return
	}
	data.RefreshFromOperationsGetServiceResponseBody(res.Object)

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
