// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/kong/terraform-provider-konnect/internal/sdk/pkg/models/operations"
	"github.com/kong/terraform-provider-konnect/internal/sdk/pkg/models/shared"
)

func (r *ServiceResourceModel) ToSharedServiceRequest() *shared.ServiceRequest {
	var caCertificates []string = nil
	for _, caCertificatesItem := range r.CaCertificates {
		caCertificates = append(caCertificates, caCertificatesItem.ValueString())
	}
	var clientCertificate *shared.ClientCertificate
	if r.ClientCertificate != nil {
		id := new(string)
		if !r.ClientCertificate.ID.IsUnknown() && !r.ClientCertificate.ID.IsNull() {
			*id = r.ClientCertificate.ID.ValueString()
		} else {
			id = nil
		}
		clientCertificate = &shared.ClientCertificate{
			ID: id,
		}
	}
	connectTimeout := new(int64)
	if !r.ConnectTimeout.IsUnknown() && !r.ConnectTimeout.IsNull() {
		*connectTimeout = r.ConnectTimeout.ValueInt64()
	} else {
		connectTimeout = nil
	}
	enabled := new(bool)
	if !r.Enabled.IsUnknown() && !r.Enabled.IsNull() {
		*enabled = r.Enabled.ValueBool()
	} else {
		enabled = nil
	}
	host := r.Host.ValueString()
	name := new(string)
	if !r.Name.IsUnknown() && !r.Name.IsNull() {
		*name = r.Name.ValueString()
	} else {
		name = nil
	}
	path := new(string)
	if !r.Path.IsUnknown() && !r.Path.IsNull() {
		*path = r.Path.ValueString()
	} else {
		path = nil
	}
	port := new(int64)
	if !r.Port.IsUnknown() && !r.Port.IsNull() {
		*port = r.Port.ValueInt64()
	} else {
		port = nil
	}
	protocol := new(shared.Protocol)
	if !r.Protocol.IsUnknown() && !r.Protocol.IsNull() {
		*protocol = shared.Protocol(r.Protocol.ValueString())
	} else {
		protocol = nil
	}
	readTimeout := new(int64)
	if !r.ReadTimeout.IsUnknown() && !r.ReadTimeout.IsNull() {
		*readTimeout = r.ReadTimeout.ValueInt64()
	} else {
		readTimeout = nil
	}
	retries := new(int64)
	if !r.Retries.IsUnknown() && !r.Retries.IsNull() {
		*retries = r.Retries.ValueInt64()
	} else {
		retries = nil
	}
	var tags []string = nil
	for _, tagsItem := range r.Tags {
		tags = append(tags, tagsItem.ValueString())
	}
	tlsVerify := new(bool)
	if !r.TLSVerify.IsUnknown() && !r.TLSVerify.IsNull() {
		*tlsVerify = r.TLSVerify.ValueBool()
	} else {
		tlsVerify = nil
	}
	tlsVerifyDepth := new(string)
	if !r.TLSVerifyDepth.IsUnknown() && !r.TLSVerifyDepth.IsNull() {
		*tlsVerifyDepth = r.TLSVerifyDepth.ValueString()
	} else {
		tlsVerifyDepth = nil
	}
	writeTimeout := new(int64)
	if !r.WriteTimeout.IsUnknown() && !r.WriteTimeout.IsNull() {
		*writeTimeout = r.WriteTimeout.ValueInt64()
	} else {
		writeTimeout = nil
	}
	out := shared.ServiceRequest{
		CaCertificates:    caCertificates,
		ClientCertificate: clientCertificate,
		ConnectTimeout:    connectTimeout,
		Enabled:           enabled,
		Host:              host,
		Name:              name,
		Path:              path,
		Port:              port,
		Protocol:          protocol,
		ReadTimeout:       readTimeout,
		Retries:           retries,
		Tags:              tags,
		TLSVerify:         tlsVerify,
		TLSVerifyDepth:    tlsVerifyDepth,
		WriteTimeout:      writeTimeout,
	}
	return &out
}

func (r *ServiceResourceModel) RefreshFromOperationsCreateServiceResponseBody(resp *operations.CreateServiceResponseBody) {
	r.ConnectTimeout = types.Int64PointerValue(resp.ConnectTimeout)
	r.CreatedAt = types.Int64PointerValue(resp.CreatedAt)
	r.Enabled = types.BoolPointerValue(resp.Enabled)
	r.Host = types.StringPointerValue(resp.Host)
	r.ID = types.StringPointerValue(resp.ID)
	r.Name = types.StringPointerValue(resp.Name)
	r.Path = types.StringPointerValue(resp.Path)
	r.Port = types.Int64PointerValue(resp.Port)
	if resp.Protocol != nil {
		r.Protocol = types.StringValue(string(*resp.Protocol))
	} else {
		r.Protocol = types.StringNull()
	}
	r.ReadTimeout = types.Int64PointerValue(resp.ReadTimeout)
	r.Retries = types.Int64PointerValue(resp.Retries)
	r.UpdatedAt = types.Int64PointerValue(resp.UpdatedAt)
	r.WriteTimeout = types.Int64PointerValue(resp.WriteTimeout)
}

func (r *ServiceResourceModel) RefreshFromOperationsGetServiceResponseBody(resp *operations.GetServiceResponseBody) {
	r.ConnectTimeout = types.Int64PointerValue(resp.ConnectTimeout)
	r.CreatedAt = types.Int64PointerValue(resp.CreatedAt)
	r.Enabled = types.BoolPointerValue(resp.Enabled)
	r.Host = types.StringPointerValue(resp.Host)
	r.ID = types.StringPointerValue(resp.ID)
	r.Name = types.StringPointerValue(resp.Name)
	r.Path = types.StringPointerValue(resp.Path)
	r.Port = types.Int64PointerValue(resp.Port)
	if resp.Protocol != nil {
		r.Protocol = types.StringValue(string(*resp.Protocol))
	} else {
		r.Protocol = types.StringNull()
	}
	r.ReadTimeout = types.Int64PointerValue(resp.ReadTimeout)
	r.Retries = types.Int64PointerValue(resp.Retries)
	r.UpdatedAt = types.Int64PointerValue(resp.UpdatedAt)
	r.WriteTimeout = types.Int64PointerValue(resp.WriteTimeout)
}

func (r *ServiceResourceModel) RefreshFromOperationsUpsertServiceResponseBody(resp *operations.UpsertServiceResponseBody) {
	r.ConnectTimeout = types.Int64PointerValue(resp.ConnectTimeout)
	r.CreatedAt = types.Int64PointerValue(resp.CreatedAt)
	r.Enabled = types.BoolPointerValue(resp.Enabled)
	r.Host = types.StringPointerValue(resp.Host)
	r.ID = types.StringPointerValue(resp.ID)
	r.Name = types.StringPointerValue(resp.Name)
	r.Path = types.StringPointerValue(resp.Path)
	r.Port = types.Int64PointerValue(resp.Port)
	if resp.Protocol != nil {
		r.Protocol = types.StringValue(string(*resp.Protocol))
	} else {
		r.Protocol = types.StringNull()
	}
	r.ReadTimeout = types.Int64PointerValue(resp.ReadTimeout)
	r.Retries = types.Int64PointerValue(resp.Retries)
	r.UpdatedAt = types.Int64PointerValue(resp.UpdatedAt)
	r.WriteTimeout = types.Int64PointerValue(resp.WriteTimeout)
}
