// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/kong/terraform-provider-konnect/internal/sdk/pkg/models/shared"
	"net/http"
)

type CreatePluginRequest struct {
	// The UUID of your control plane. This variable is available in the Konnect manager
	ControlPlaneID string `pathParam:"style=simple,explode=false,name=controlPlaneId"`
	// Plugin request body
	PluginRequest *shared.PluginRequest `request:"mediaType=application/json"`
}

func (o *CreatePluginRequest) GetControlPlaneID() string {
	if o == nil {
		return ""
	}
	return o.ControlPlaneID
}

func (o *CreatePluginRequest) GetPluginRequest() *shared.PluginRequest {
	if o == nil {
		return nil
	}
	return o.PluginRequest
}

// CreatePluginResponseBody - Invalid Plugin
type CreatePluginResponseBody struct {
}

type CreatePluginResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Successfully created plugin
	Plugin *shared.Plugin
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Invalid Plugin
	Object *CreatePluginResponseBody
}

func (o *CreatePluginResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *CreatePluginResponse) GetPlugin() *shared.Plugin {
	if o == nil {
		return nil
	}
	return o.Plugin
}

func (o *CreatePluginResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *CreatePluginResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *CreatePluginResponse) GetObject() *CreatePluginResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
