// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/kong/terraform-provider-konnect/internal/sdk/pkg/models/shared"
	"net/http"
)

type CreateBasicAuthRequest struct {
	// Description of the new Basic-auth credential for creation
	CreateBasicAuth shared.CreateBasicAuth `request:"mediaType=application/json"`
	// The UUID of your control plane. This variable is available in the Konnect manager.
	ControlPlaneID string `pathParam:"style=simple,explode=false,name=controlPlaneId"`
}

func (o *CreateBasicAuthRequest) GetCreateBasicAuth() shared.CreateBasicAuth {
	if o == nil {
		return shared.CreateBasicAuth{}
	}
	return o.CreateBasicAuth
}

func (o *CreateBasicAuthRequest) GetControlPlaneID() string {
	if o == nil {
		return ""
	}
	return o.ControlPlaneID
}

// CreateBasicAuthResponseBody - Invalid Basic-auth credential
type CreateBasicAuthResponseBody struct {
}

type CreateBasicAuthResponse struct {
	// Successfully created Basic-auth credential
	BasicAuth *shared.BasicAuth
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Unauthorized
	UnauthorizedError *shared.UnauthorizedError
	// Invalid Basic-auth credential
	Object *CreateBasicAuthResponseBody
}

func (o *CreateBasicAuthResponse) GetBasicAuth() *shared.BasicAuth {
	if o == nil {
		return nil
	}
	return o.BasicAuth
}

func (o *CreateBasicAuthResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *CreateBasicAuthResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *CreateBasicAuthResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *CreateBasicAuthResponse) GetUnauthorizedError() *shared.UnauthorizedError {
	if o == nil {
		return nil
	}
	return o.UnauthorizedError
}

func (o *CreateBasicAuthResponse) GetObject() *CreateBasicAuthResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
