// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"konnect/internal/sdk/pkg/models/shared"
	"net/http"
)

// CreateRuntimeGroupServiceUnavailableErrorStatus - The HTTP status code.
type CreateRuntimeGroupServiceUnavailableErrorStatus int64

const (
	CreateRuntimeGroupServiceUnavailableErrorStatusFiveHundredAndThree CreateRuntimeGroupServiceUnavailableErrorStatus = 503
)

func (e CreateRuntimeGroupServiceUnavailableErrorStatus) ToPointer() *CreateRuntimeGroupServiceUnavailableErrorStatus {
	return &e
}

func (e *CreateRuntimeGroupServiceUnavailableErrorStatus) UnmarshalJSON(data []byte) error {
	var v int64
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case 503:
		*e = CreateRuntimeGroupServiceUnavailableErrorStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CreateRuntimeGroupServiceUnavailableErrorStatus: %v", v)
	}
}

// CreateRuntimeGroupServiceUnavailableError - Error response for temporary service unavailability.
type CreateRuntimeGroupServiceUnavailableError struct {
	// Details about the error.
	Detail *string `json:"detail,omitempty"`
	// The Konnect traceback code
	Instance string `json:"instance"`
	// The HTTP status code.
	Status CreateRuntimeGroupServiceUnavailableErrorStatus `json:"status"`
	// The error response code.
	Title string `json:"title"`
}

// CreateRuntimeGroupInternalServerErrorStatus - The HTTP status code.
type CreateRuntimeGroupInternalServerErrorStatus int64

const (
	CreateRuntimeGroupInternalServerErrorStatusFiveHundred CreateRuntimeGroupInternalServerErrorStatus = 500
)

func (e CreateRuntimeGroupInternalServerErrorStatus) ToPointer() *CreateRuntimeGroupInternalServerErrorStatus {
	return &e
}

func (e *CreateRuntimeGroupInternalServerErrorStatus) UnmarshalJSON(data []byte) error {
	var v int64
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case 500:
		*e = CreateRuntimeGroupInternalServerErrorStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CreateRuntimeGroupInternalServerErrorStatus: %v", v)
	}
}

// CreateRuntimeGroupInternalServerError - The error response object.
type CreateRuntimeGroupInternalServerError struct {
	// Details about the error.
	Detail *string `json:"detail,omitempty"`
	// The Konnect traceback code
	Instance string `json:"instance"`
	// The HTTP status code.
	Status CreateRuntimeGroupInternalServerErrorStatus `json:"status"`
	// The error response code.
	Title string `json:"title"`
}

type CreateRuntimeGroupResponse struct {
	// Bad Request
	BadRequestError *shared.BadRequestError
	// Conflict
	ConflictError *shared.ConflictError
	ContentType   string
	// Permission denied
	ForbiddenError *shared.ForbiddenError
	// Internal Server Error
	InternalServerError *CreateRuntimeGroupInternalServerError
	// A response to creating a runtime group.
	RuntimeGroup *shared.RuntimeGroup
	StatusCode   int
	RawResponse  *http.Response
	// Service Unavailable
	ServiceUnavailableError *CreateRuntimeGroupServiceUnavailableError
	// Unauthenticated
	UnauthorizedError *shared.UnauthorizedError
}
