// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"konnect/internal/sdk/pkg/models/shared"
	"net/http"
)

type CreateRouteRequest struct {
	Route *shared.Route `request:"mediaType=application/json"`
	// The ID of your runtime group. This variable is available in the Konnect manager
	RuntimeGroupID string `pathParam:"style=simple,explode=false,name=runtimeGroupId"`
}

// CreateRoute400ApplicationJSON - Invalid route
type CreateRoute400ApplicationJSON struct {
}

type CreateRouteResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Successfully created route
	Route *shared.Route
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Invalid route
	CreateRoute400ApplicationJSONObject *CreateRoute400ApplicationJSON
}
