// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"Konnect/internal/sdk/pkg/models/shared"
	"net/http"
)

// CreateTeamRequestBody - The request schema for the create team request.
//
// If you pass the same `name` and `description` of an existing team in the request, a team with the same `name` and `description` will be created. The two teams will have different `team_id` values to differentiate them.
type CreateTeamRequestBody struct {
	// The description of the new team.
	Description *string `json:"description,omitempty"`
	// A name for the team being created.
	Name string `json:"name"`
}

type CreateTeamResponse struct {
	// Bad Request
	BadRequestError *shared.BadRequestError
	ContentType     string
	// Permission denied
	ForbiddenError *shared.ForbiddenError
	StatusCode     int
	RawResponse    *http.Response
	// A response including a single team.
	Team *shared.Team
}
