// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/kong/terraform-provider-konnect/internal/sdk/pkg/models/shared"
	"net/http"
)

type CreateKeyRequest struct {
	// Description of the new Key for creation
	CreateKey shared.CreateKey `request:"mediaType=application/json"`
	// The UUID of your control plane. This variable is available in the Konnect manager.
	ControlPlaneID string `pathParam:"style=simple,explode=false,name=controlPlaneId"`
}

func (o *CreateKeyRequest) GetCreateKey() shared.CreateKey {
	if o == nil {
		return shared.CreateKey{}
	}
	return o.CreateKey
}

func (o *CreateKeyRequest) GetControlPlaneID() string {
	if o == nil {
		return ""
	}
	return o.ControlPlaneID
}

// CreateKeyResponseBody - Invalid Key
type CreateKeyResponseBody struct {
}

type CreateKeyResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Successfully created Key
	Key *shared.Key
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Unauthorized
	UnauthorizedError *shared.UnauthorizedError
	// Invalid Key
	Object *CreateKeyResponseBody
}

func (o *CreateKeyResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *CreateKeyResponse) GetKey() *shared.Key {
	if o == nil {
		return nil
	}
	return o.Key
}

func (o *CreateKeyResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *CreateKeyResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *CreateKeyResponse) GetUnauthorizedError() *shared.UnauthorizedError {
	if o == nil {
		return nil
	}
	return o.UnauthorizedError
}

func (o *CreateKeyResponse) GetObject() *CreateKeyResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
