// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/kong/terraform-provider-konnect/internal/sdk/pkg/models/shared"
	"net/http"
)

var CreateCpServerList = []string{
	"https://us.api.konghq.com/v1",
	"https://us.api.konghq.com/v1",
}

type CreateCpResponse struct {
	// Validation Error
	BadRequestError *shared.BadRequestError
	// HTTP response content type for this operation
	ContentType string
	// Permission denied
	ForbiddenError *shared.ForbiddenError
	// A response to creating a control plane.
	MeshControlPlane *shared.MeshControlPlane
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Unauthorized Error
	UnauthorizedError *shared.UnauthorizedError
}

func (o *CreateCpResponse) GetBadRequestError() *shared.BadRequestError {
	if o == nil {
		return nil
	}
	return o.BadRequestError
}

func (o *CreateCpResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *CreateCpResponse) GetForbiddenError() *shared.ForbiddenError {
	if o == nil {
		return nil
	}
	return o.ForbiddenError
}

func (o *CreateCpResponse) GetMeshControlPlane() *shared.MeshControlPlane {
	if o == nil {
		return nil
	}
	return o.MeshControlPlane
}

func (o *CreateCpResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *CreateCpResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *CreateCpResponse) GetUnauthorizedError() *shared.UnauthorizedError {
	if o == nil {
		return nil
	}
	return o.UnauthorizedError
}
