// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"Konnect/internal/sdk/pkg/models/shared"
	"net/http"
)

type DeleteReportRequest struct {
	// The report's ID
	ReportID string `pathParam:"style=simple,explode=false,name=reportId"`
}

// DeleteReport429ApplicationProblemPlusJSON - The error response object.
type DeleteReport429ApplicationProblemPlusJSON struct {
	// Details about the error.
	Detail *string `json:"detail,omitempty"`
	// The Konnect traceback code
	Instance *string `json:"instance,omitempty"`
	// The HTTP status code.
	Status *int64 `json:"status,omitempty"`
	// The error response code.
	Title *string `json:"title,omitempty"`
	// Documentation for this error.
	Type *string `json:"type,omitempty"`
}

// DeleteReport403ApplicationProblemPlusJSON - The error object.
type DeleteReport403ApplicationProblemPlusJSON struct {
	// Information about the error response.
	Detail *string `json:"detail,omitempty"`
	// Konnect traceback error code.
	Instance *string `json:"instance,omitempty"`
	// HTTP status code.
	Status *int64 `json:"status,omitempty"`
	// HTTP status code
	Title *string `json:"title,omitempty"`
	// Documentation for this error.
	Type *string `json:"type,omitempty"`
}

type DeleteReportResponse struct {
	// Bad Request
	BadRequestError *shared.BadRequestError
	ContentType     string
	// Not Found
	NotFoundError *shared.NotFoundError
	StatusCode    int
	RawResponse   *http.Response
	// Permission denied
	DeleteReport403ApplicationProblemPlusJSONObject *DeleteReport403ApplicationProblemPlusJSON
	// Too many requests
	DeleteReport429ApplicationProblemPlusJSONObject *DeleteReport429ApplicationProblemPlusJSON
}
