// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type DeleteControlPlanesControlPlaneIDCoreEntitiesCertificatesCertificateIDSnisSNIIDRequest struct {
	// ID of the Certificate to lookup
	CertificateID string `pathParam:"style=simple,explode=false,name=CertificateId"`
	// ID of the SNI to lookup
	SNIID string `pathParam:"style=simple,explode=false,name=SNIId"`
	// The UUID of your control plane. This variable is available in the Konnect manager.
	ControlPlaneID string `pathParam:"style=simple,explode=false,name=controlPlaneId"`
}

func (o *DeleteControlPlanesControlPlaneIDCoreEntitiesCertificatesCertificateIDSnisSNIIDRequest) GetCertificateID() string {
	if o == nil {
		return ""
	}
	return o.CertificateID
}

func (o *DeleteControlPlanesControlPlaneIDCoreEntitiesCertificatesCertificateIDSnisSNIIDRequest) GetSNIID() string {
	if o == nil {
		return ""
	}
	return o.SNIID
}

func (o *DeleteControlPlanesControlPlaneIDCoreEntitiesCertificatesCertificateIDSnisSNIIDRequest) GetControlPlaneID() string {
	if o == nil {
		return ""
	}
	return o.ControlPlaneID
}

type DeleteControlPlanesControlPlaneIDCoreEntitiesCertificatesCertificateIDSnisSNIIDResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *DeleteControlPlanesControlPlaneIDCoreEntitiesCertificatesCertificateIDSnisSNIIDResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *DeleteControlPlanesControlPlaneIDCoreEntitiesCertificatesCertificateIDSnisSNIIDResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *DeleteControlPlanesControlPlaneIDCoreEntitiesCertificatesCertificateIDSnisSNIIDResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
