// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/kong/terraform-provider-konnect/internal/sdk/pkg/models/shared"
	"net/http"
)

type DeleteControlPlaneRequest struct {
	// The control plane ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *DeleteControlPlaneRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

// DeleteControlPlaneControlPlanesStatus - The HTTP status code.
type DeleteControlPlaneControlPlanesStatus int64

const (
	DeleteControlPlaneControlPlanesStatusFiveHundredAndThree DeleteControlPlaneControlPlanesStatus = 503
)

func (e DeleteControlPlaneControlPlanesStatus) ToPointer() *DeleteControlPlaneControlPlanesStatus {
	return &e
}

func (e *DeleteControlPlaneControlPlanesStatus) UnmarshalJSON(data []byte) error {
	var v int64
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case 503:
		*e = DeleteControlPlaneControlPlanesStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for DeleteControlPlaneControlPlanesStatus: %v", v)
	}
}

// DeleteControlPlaneServiceUnavailableError - Error response for temporary service unavailability.
type DeleteControlPlaneServiceUnavailableError struct {
	// Details about the error.
	Detail *string `json:"detail,omitempty"`
	// The Konnect traceback code
	Instance string `json:"instance"`
	// The HTTP status code.
	Status DeleteControlPlaneControlPlanesStatus `json:"status"`
	// The error response code.
	Title string `json:"title"`
}

func (o *DeleteControlPlaneServiceUnavailableError) GetDetail() *string {
	if o == nil {
		return nil
	}
	return o.Detail
}

func (o *DeleteControlPlaneServiceUnavailableError) GetInstance() string {
	if o == nil {
		return ""
	}
	return o.Instance
}

func (o *DeleteControlPlaneServiceUnavailableError) GetStatus() DeleteControlPlaneControlPlanesStatus {
	if o == nil {
		return DeleteControlPlaneControlPlanesStatus(0)
	}
	return o.Status
}

func (o *DeleteControlPlaneServiceUnavailableError) GetTitle() string {
	if o == nil {
		return ""
	}
	return o.Title
}

// DeleteControlPlaneStatus - The HTTP status code.
type DeleteControlPlaneStatus int64

const (
	DeleteControlPlaneStatusFiveHundred DeleteControlPlaneStatus = 500
)

func (e DeleteControlPlaneStatus) ToPointer() *DeleteControlPlaneStatus {
	return &e
}

func (e *DeleteControlPlaneStatus) UnmarshalJSON(data []byte) error {
	var v int64
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case 500:
		*e = DeleteControlPlaneStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for DeleteControlPlaneStatus: %v", v)
	}
}

// DeleteControlPlaneInternalServerError - The error response object.
type DeleteControlPlaneInternalServerError struct {
	// Details about the error.
	Detail *string `json:"detail,omitempty"`
	// The Konnect traceback code
	Instance string `json:"instance"`
	// The HTTP status code.
	Status DeleteControlPlaneStatus `json:"status"`
	// The error response code.
	Title string `json:"title"`
}

func (o *DeleteControlPlaneInternalServerError) GetDetail() *string {
	if o == nil {
		return nil
	}
	return o.Detail
}

func (o *DeleteControlPlaneInternalServerError) GetInstance() string {
	if o == nil {
		return ""
	}
	return o.Instance
}

func (o *DeleteControlPlaneInternalServerError) GetStatus() DeleteControlPlaneStatus {
	if o == nil {
		return DeleteControlPlaneStatus(0)
	}
	return o.Status
}

func (o *DeleteControlPlaneInternalServerError) GetTitle() string {
	if o == nil {
		return ""
	}
	return o.Title
}

type DeleteControlPlaneResponse struct {
	// Bad Request
	BadRequestError *shared.BadRequestError
	// HTTP response content type for this operation
	ContentType string
	// Permission denied
	ForbiddenError *shared.ForbiddenError
	// Internal Server Error
	InternalServerError *DeleteControlPlaneInternalServerError
	// Not Found
	NotFoundError *shared.NotFoundError
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Service Unavailable
	ServiceUnavailableError *DeleteControlPlaneServiceUnavailableError
	// Unauthenticated
	UnauthorizedError *shared.UnauthorizedError
}

func (o *DeleteControlPlaneResponse) GetBadRequestError() *shared.BadRequestError {
	if o == nil {
		return nil
	}
	return o.BadRequestError
}

func (o *DeleteControlPlaneResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *DeleteControlPlaneResponse) GetForbiddenError() *shared.ForbiddenError {
	if o == nil {
		return nil
	}
	return o.ForbiddenError
}

func (o *DeleteControlPlaneResponse) GetInternalServerError() *DeleteControlPlaneInternalServerError {
	if o == nil {
		return nil
	}
	return o.InternalServerError
}

func (o *DeleteControlPlaneResponse) GetNotFoundError() *shared.NotFoundError {
	if o == nil {
		return nil
	}
	return o.NotFoundError
}

func (o *DeleteControlPlaneResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *DeleteControlPlaneResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *DeleteControlPlaneResponse) GetServiceUnavailableError() *DeleteControlPlaneServiceUnavailableError {
	if o == nil {
		return nil
	}
	return o.ServiceUnavailableError
}

func (o *DeleteControlPlaneResponse) GetUnauthorizedError() *shared.UnauthorizedError {
	if o == nil {
		return nil
	}
	return o.UnauthorizedError
}
