// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type DeleteKeySetRequest struct {
	// The unique identifier or the `name` attribute of the Key Set that should be associated to the newly-created Key.
	KeySetIDOrName string `pathParam:"style=simple,explode=false,name=key-set_id_or_name"`
	// The ID of your runtime group. This variable is available in the Konnect manager
	RuntimeGroupID string `pathParam:"style=simple,explode=false,name=runtimeGroupId"`
}

type DeleteKeySetResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
