// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type DeleteControlPlanesControlPlaneIDCoreEntitiesConsumersConsumerIDPluginsPluginIDRequest struct {
	// ID of the Consumer to lookup
	ConsumerID string `pathParam:"style=simple,explode=false,name=ConsumerId"`
	// ID of the Plugin to lookup
	PluginID string `pathParam:"style=simple,explode=false,name=PluginId"`
	// The UUID of your control plane. This variable is available in the Konnect manager.
	ControlPlaneID string `pathParam:"style=simple,explode=false,name=controlPlaneId"`
}

func (o *DeleteControlPlanesControlPlaneIDCoreEntitiesConsumersConsumerIDPluginsPluginIDRequest) GetConsumerID() string {
	if o == nil {
		return ""
	}
	return o.ConsumerID
}

func (o *DeleteControlPlanesControlPlaneIDCoreEntitiesConsumersConsumerIDPluginsPluginIDRequest) GetPluginID() string {
	if o == nil {
		return ""
	}
	return o.PluginID
}

func (o *DeleteControlPlanesControlPlaneIDCoreEntitiesConsumersConsumerIDPluginsPluginIDRequest) GetControlPlaneID() string {
	if o == nil {
		return ""
	}
	return o.ControlPlaneID
}

type DeleteControlPlanesControlPlaneIDCoreEntitiesConsumersConsumerIDPluginsPluginIDResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *DeleteControlPlanesControlPlaneIDCoreEntitiesConsumersConsumerIDPluginsPluginIDResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *DeleteControlPlanesControlPlaneIDCoreEntitiesConsumersConsumerIDPluginsPluginIDResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *DeleteControlPlanesControlPlaneIDCoreEntitiesConsumersConsumerIDPluginsPluginIDResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
