// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type DeleteDpClientCertificatesCertIDRequest struct {
	CertificateID string `pathParam:"style=simple,explode=false,name=certificateId"`
	// The ID of your runtime group. This variable is available in the Konnect manager
	RuntimeGroupID string `pathParam:"style=simple,explode=false,name=runtimeGroupId"`
}

type DeleteDpClientCertificatesCertIDResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
