// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"Konnect/internal/sdk/pkg/models/shared"
	"net/http"
)

type FetchSniWithCertificateRequest struct {
	// The unique identifier of the Certificate to retrieve.
	CertificateID string `pathParam:"style=simple,explode=false,name=certificate_id"`
	// Offset from which to return the next set of resources. Use the value of the 'offset' field from the response of a list operation as input here to paginate through all the resources
	Offset *string `queryParam:"style=form,explode=true,name=offset"`
	// The ID of your runtime group. This variable is available in the Konnect manager
	RuntimeGroupID string `pathParam:"style=simple,explode=false,name=runtimeGroupId"`
	// Number of resources to be returned.
	Size *int64 `queryParam:"style=form,explode=true,name=size"`
	// The unique identifier or the name of the SNI to retrieve.
	SniID string `pathParam:"style=simple,explode=false,name=sni_id"`
	// A list of tags to filter the list of resources on. Multiple tags can be concatenated using ',' to mean AND or using '/' to mean OR.
	Tags *string `queryParam:"style=form,explode=true,name=tags"`
}

type FetchSniWithCertificateResponse struct {
	ContentType string
	// Successfully fetched SNI
	Sni         *shared.Sni
	StatusCode  int
	RawResponse *http.Response
}
