// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"Konnect/internal/sdk/pkg/models/shared"
	"net/http"
)

// GetAuthenticationSettings200ApplicationJSON - Response for authentication settings endpoint
type GetAuthenticationSettings200ApplicationJSON struct {
	// The organization has basic auth enabled.
	BasicAuthEnabled *bool `json:"basic_auth_enabled,omitempty"`
	// IdP groups determine the Konnect teams a user has.
	IdpMappingEnabled *bool `json:"idp_mapping_enabled,omitempty"`
	// A Konnect Identity Admin assigns teams to a user.
	KonnectMappingEnabled *bool `json:"konnect_mapping_enabled,omitempty"`
	// The organization has OIDC disabled.
	OidcAuthEnabled *bool `json:"oidc_auth_enabled,omitempty"`
}

type GetAuthenticationSettingsResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Unauthenticated
	UnauthorizedError *shared.UnauthorizedError
	// Response for authentication settings endpoint
	GetAuthenticationSettings200ApplicationJSONObject *GetAuthenticationSettings200ApplicationJSON
}
