// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"Konnect/internal/sdk/pkg/models/shared"
	"net/http"
)

type GetAPIProductVersionSpecRequest struct {
	// The API product identifier
	APIProductID string `pathParam:"style=simple,explode=false,name=apiProductId"`
	// The API product version identifier
	ProductVersionID string `pathParam:"style=simple,explode=false,name=productVersionId"`
	// The API product version specification identifier
	SpecificationID string `pathParam:"style=simple,explode=false,name=specificationId"`
}

type GetAPIProductVersionSpecResponse struct {
	// API product version specification
	APIProductVersionSpec *shared.APIProductVersionSpec
	ContentType           string
	// Forbidden
	ForbiddenError *shared.ForbiddenError
	// Not Found
	NotFoundError *shared.NotFoundError
	StatusCode    int
	RawResponse   *http.Response
	// Unauthorized
	UnauthorizedError *shared.UnauthorizedError
}
