// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"Konnect/internal/sdk/pkg/models/shared"
	"net/http"
)

type GetAPIProductRequest struct {
	// API product identifier
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

type GetAPIProductResponse struct {
	// API product
	APIProduct  *shared.APIProduct
	ContentType string
	// Forbidden
	ForbiddenError *shared.ForbiddenError
	// Not Found
	NotFoundError *shared.NotFoundError
	StatusCode    int
	RawResponse   *http.Response
	// Unauthorized
	UnauthorizedError *shared.UnauthorizedError
}
