// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"Konnect/internal/sdk/pkg/models/shared"
	"encoding/json"
	"fmt"
	"net/http"
	"time"
)

// GetAuditLogWebhookStatus200ApplicationJSONWebhookStatus - Current status of a webhook. `active` indicates the webhook is sending or ready to send requests.
// `inactive` indicates the webhook has been turned off due to failed attempts.
type GetAuditLogWebhookStatus200ApplicationJSONWebhookStatus string

const (
	GetAuditLogWebhookStatus200ApplicationJSONWebhookStatusActive   GetAuditLogWebhookStatus200ApplicationJSONWebhookStatus = "active"
	GetAuditLogWebhookStatus200ApplicationJSONWebhookStatusInactive GetAuditLogWebhookStatus200ApplicationJSONWebhookStatus = "inactive"
)

func (e GetAuditLogWebhookStatus200ApplicationJSONWebhookStatus) ToPointer() *GetAuditLogWebhookStatus200ApplicationJSONWebhookStatus {
	return &e
}

func (e *GetAuditLogWebhookStatus200ApplicationJSONWebhookStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "active":
		fallthrough
	case "inactive":
		*e = GetAuditLogWebhookStatus200ApplicationJSONWebhookStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetAuditLogWebhookStatus200ApplicationJSONWebhookStatus: %v", v)
	}
}

// GetAuditLogWebhookStatus200ApplicationJSON - Get response for audit log webhook status
type GetAuditLogWebhookStatus200ApplicationJSON struct {
	// The last time a request was made to the webhook, regardless of outcome.
	LastAttemptAt *time.Time `json:"last_attempt_at,omitempty"`
	// The last response code received from the webhook.
	LastResponseCode *int64 `json:"last_response_code,omitempty"`
	// The last message received from the webhook. Useful for debugging.
	LastResponseMessage *string `json:"last_response_message,omitempty"`
	// Configured status of a webhook. `enabled` indicates the client will accept requests.
	// `disabled` indicates the client will not accept requests.
	WebhookEnabled *bool `json:"webhook_enabled,omitempty"`
	// Current status of a webhook. `active` indicates the webhook is sending or ready to send requests.
	// `inactive` indicates the webhook has been turned off due to failed attempts.
	WebhookStatus *GetAuditLogWebhookStatus200ApplicationJSONWebhookStatus `json:"webhook_status,omitempty"`
}

type GetAuditLogWebhookStatusResponse struct {
	ContentType string
	// Forbidden
	ForbiddenError *shared.ForbiddenError
	StatusCode     int
	RawResponse    *http.Response
	// Unauthorized
	UnauthorizedError *shared.UnauthorizedError
	// Get response for audit log webhook status
	GetAuditLogWebhookStatus200ApplicationJSONObject *GetAuditLogWebhookStatus200ApplicationJSON
}
