// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/kong/terraform-provider-konnect/internal/sdk/pkg/models/shared"
	"github.com/kong/terraform-provider-konnect/internal/sdk/pkg/utils"
	"net/http"
)

type GetControlPlanesControlPlaneIDCoreEntitiesConsumersConsumerIDKeyAuthRequest struct {
	// ID of the Consumer to lookup
	ConsumerID string `pathParam:"style=simple,explode=false,name=ConsumerId"`
	// The UUID of your control plane. This variable is available in the Konnect manager.
	ControlPlaneID string `pathParam:"style=simple,explode=false,name=controlPlaneId"`
	// Offset from which to return the next set of resources. Use the value of the 'offset' field from the response of a list operation as input here to paginate through all the resources
	Offset *string `queryParam:"style=form,explode=true,name=offset"`
	// Number of resources to be returned.
	Size *int64 `default:"100" queryParam:"style=form,explode=true,name=size"`
	// A list of tags to filter the list of resources on. Multiple tags can be concatenated using ',' to mean AND or using '/' to mean OR.
	Tags *string `queryParam:"style=form,explode=true,name=tags"`
}

func (g GetControlPlanesControlPlaneIDCoreEntitiesConsumersConsumerIDKeyAuthRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetControlPlanesControlPlaneIDCoreEntitiesConsumersConsumerIDKeyAuthRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *GetControlPlanesControlPlaneIDCoreEntitiesConsumersConsumerIDKeyAuthRequest) GetConsumerID() string {
	if o == nil {
		return ""
	}
	return o.ConsumerID
}

func (o *GetControlPlanesControlPlaneIDCoreEntitiesConsumersConsumerIDKeyAuthRequest) GetControlPlaneID() string {
	if o == nil {
		return ""
	}
	return o.ControlPlaneID
}

func (o *GetControlPlanesControlPlaneIDCoreEntitiesConsumersConsumerIDKeyAuthRequest) GetOffset() *string {
	if o == nil {
		return nil
	}
	return o.Offset
}

func (o *GetControlPlanesControlPlaneIDCoreEntitiesConsumersConsumerIDKeyAuthRequest) GetSize() *int64 {
	if o == nil {
		return nil
	}
	return o.Size
}

func (o *GetControlPlanesControlPlaneIDCoreEntitiesConsumersConsumerIDKeyAuthRequest) GetTags() *string {
	if o == nil {
		return nil
	}
	return o.Tags
}

// GetControlPlanesControlPlaneIDCoreEntitiesConsumersConsumerIDKeyAuthResponseBody - A successful response listing API-keys
type GetControlPlanesControlPlaneIDCoreEntitiesConsumersConsumerIDKeyAuthResponseBody struct {
	Data []shared.APIKey `json:"data,omitempty"`
	// Offset is used to paginate through the API. Provide this value to the next list operation to fetch the next page
	Offset *string `json:"offset,omitempty"`
}

func (o *GetControlPlanesControlPlaneIDCoreEntitiesConsumersConsumerIDKeyAuthResponseBody) GetData() []shared.APIKey {
	if o == nil {
		return nil
	}
	return o.Data
}

func (o *GetControlPlanesControlPlaneIDCoreEntitiesConsumersConsumerIDKeyAuthResponseBody) GetOffset() *string {
	if o == nil {
		return nil
	}
	return o.Offset
}

type GetControlPlanesControlPlaneIDCoreEntitiesConsumersConsumerIDKeyAuthResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// A successful response listing API-keys
	Object *GetControlPlanesControlPlaneIDCoreEntitiesConsumersConsumerIDKeyAuthResponseBody
}

func (o *GetControlPlanesControlPlaneIDCoreEntitiesConsumersConsumerIDKeyAuthResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetControlPlanesControlPlaneIDCoreEntitiesConsumersConsumerIDKeyAuthResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetControlPlanesControlPlaneIDCoreEntitiesConsumersConsumerIDKeyAuthResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetControlPlanesControlPlaneIDCoreEntitiesConsumersConsumerIDKeyAuthResponse) GetObject() *GetControlPlanesControlPlaneIDCoreEntitiesConsumersConsumerIDKeyAuthResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
