// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"Konnect/internal/sdk/pkg/models/shared"
	"net/http"
)

type GetIdpTeamMappingsRequest struct {
	// Determines which page of the entities to retrieve.
	PageNumber *int64 `queryParam:"style=form,explode=true,name=page[number]"`
	// The maximum number of items to include per page. The last page of a collection may include fewer items.
	PageSize *int64 `queryParam:"style=form,explode=true,name=page[size]"`
}

// GetIdpTeamMappings412ApplicationProblemPlusJSON - The error response object.
type GetIdpTeamMappings412ApplicationProblemPlusJSON struct {
	// Details about the error response.
	Detail *string `json:"detail,omitempty"`
	// The Konnect traceback code.
	Instance *string `json:"instance,omitempty"`
	// The HTTP status code.
	Status *int64 `json:"status,omitempty"`
	// The error response code.
	Title *string `json:"title,omitempty"`
}

type GetIdpTeamMappings200ApplicationJSONData struct {
	// Group names.
	Group *string `json:"group,omitempty"`
	// Team ID's that belong to the specified group.
	TeamIds []string `json:"team_ids,omitempty"`
}

// GetIdpTeamMappings200ApplicationJSONMetaPage - The page object.
type GetIdpTeamMappings200ApplicationJSONMetaPage struct {
	// Page number.
	Number *int64 `json:"number,omitempty"`
	// Page size.
	Size *int64 `json:"size,omitempty"`
	// Total number of results.
	Total *int64 `json:"total,omitempty"`
}

// GetIdpTeamMappings200ApplicationJSONMeta - Contains pagination data.
type GetIdpTeamMappings200ApplicationJSONMeta struct {
	// The page object.
	Page *GetIdpTeamMappings200ApplicationJSONMetaPage `json:"page,omitempty"`
}

// GetIdpTeamMappings200ApplicationJSON - A paginated list response for a collection of team mappings.
type GetIdpTeamMappings200ApplicationJSON struct {
	Data []GetIdpTeamMappings200ApplicationJSONData `json:"data,omitempty"`
	// Contains pagination data.
	Meta *GetIdpTeamMappings200ApplicationJSONMeta `json:"meta,omitempty"`
}

type GetIdpTeamMappingsResponse struct {
	ContentType string
	// Permission denied
	ForbiddenError *shared.ForbiddenError
	// Not Found
	NotFoundError *shared.NotFoundError
	StatusCode    int
	RawResponse   *http.Response
	// Unauthenticated
	UnauthorizedError *shared.UnauthorizedError
	// A paginated list response for a collection of team mappings.
	GetIdpTeamMappings200ApplicationJSONObject *GetIdpTeamMappings200ApplicationJSON
	// Precondition Failed
	GetIdpTeamMappings412ApplicationProblemPlusJSONObject *GetIdpTeamMappings412ApplicationProblemPlusJSON
}
