// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type GetKeySetRequest struct {
	// The unique identifier or the `name` attribute of the Key Set that should be associated to the newly-created Key.
	KeySetIDOrName string `pathParam:"style=simple,explode=false,name=key-set_id_or_name"`
	// Offset from which to return the next set of resources. Use the value of the 'offset' field from the response of a list operation as input here to paginate through all the resources
	Offset *string `queryParam:"style=form,explode=true,name=offset"`
	// The ID of your runtime group. This variable is available in the Konnect manager
	RuntimeGroupID string `pathParam:"style=simple,explode=false,name=runtimeGroupId"`
	// Number of resources to be returned.
	Size *int64 `queryParam:"style=form,explode=true,name=size"`
	// A list of tags to filter the list of resources on. Multiple tags can be concatenated using ',' to mean AND or using '/' to mean OR.
	Tags *string `queryParam:"style=form,explode=true,name=tags"`
}

// GetKeySet200ApplicationJSON - Key set object response body
type GetKeySet200ApplicationJSON struct {
	// Unix epoch when the resource was last created.
	CreatedAt *int64  `json:"created_at,omitempty"`
	ID        *string `json:"id,omitempty"`
	// The name to associate with the given key-set.
	//
	Name *string `json:"name,omitempty"`
	// Offset is used to paginate through the API. Provide this value to the next list operation to fetch the next page
	//
	Next *string `json:"next,omitempty"`
	// The name to associate with the given key-set.
	//
	Tags []string `json:"tags,omitempty"`
	// Unix epoch when the resource was last updated.
	//
	UpdatedAt *int64 `json:"updated_at,omitempty"`
}

type GetKeySetResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Key set object response body
	GetKeySet200ApplicationJSONObject *GetKeySet200ApplicationJSON
}
