// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"Konnect/internal/sdk/pkg/models/shared"
	"net/http"
)

type GetManyAPIProductVersionSpecRequest struct {
	// The API product identifier
	APIProductID string `pathParam:"style=simple,explode=false,name=apiProductId"`
	// The API product version identifier
	ProductVersionID string `pathParam:"style=simple,explode=false,name=productVersionId"`
}

// GetManyAPIProductVersionSpecListAPIProductVersionSpecResponse - List of API product version specification
type GetManyAPIProductVersionSpecListAPIProductVersionSpecResponse struct {
	Data []shared.APIProductVersionSpec `json:"data"`
	// returns the pagination information
	Meta shared.PaginatedMeta `json:"meta"`
}

type GetManyAPIProductVersionSpecResponse struct {
	ContentType string
	// Forbidden
	ForbiddenError *shared.ForbiddenError
	// List of API product version specification
	ListAPIProductVersionSpecResponse *GetManyAPIProductVersionSpecListAPIProductVersionSpecResponse
	// Not Found
	NotFoundError *shared.NotFoundError
	StatusCode    int
	RawResponse   *http.Response
	// Unauthorized
	UnauthorizedError *shared.UnauthorizedError
}
