// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type GetRuntimeGroupIDCoreEntitiesConsumerGroupsRequest struct {
	// Offset from which to return the next set of resources. Use the value of the 'offset' field from the response of a list operation as input here to paginate through all the resources
	Offset *string `queryParam:"style=form,explode=true,name=offset"`
	// The ID of your runtime group. This variable is available in the Konnect manager
	RuntimeGroupID string `pathParam:"style=simple,explode=false,name=runtimeGroupId"`
	// Number of resources to be returned.
	Size *int64 `queryParam:"style=form,explode=true,name=size"`
	// A list of tags to filter the list of resources on. Multiple tags can be concatenated using ',' to mean AND or using '/' to mean OR.
	Tags *string `queryParam:"style=form,explode=true,name=tags"`
}

// GetRuntimeGroupIDCoreEntitiesConsumerGroups200ApplicationXML - Example response
type GetRuntimeGroupIDCoreEntitiesConsumerGroups200ApplicationXML struct {
}

type GetRuntimeGroupIDCoreEntitiesConsumerGroups200ApplicationJSONData struct {
	// Unix epoch when the resource was created.
	CreatedAt *int64 `json:"created_at,omitempty"`
	// Consumer group ID
	ID *string `json:"id,omitempty"`
	// The name of the consumer group
	Name *string `json:"name,omitempty"`
	// An optional set of strings associated with the Consumer for grouping and filtering.
	//
	Tags []string `json:"tags,omitempty"`
	// The unix epoc representation of when the consumer group was updated.
	UpdatedAt *int64 `json:"updated_at,omitempty"`
}

// GetRuntimeGroupIDCoreEntitiesConsumerGroups200ApplicationJSON - Example response
type GetRuntimeGroupIDCoreEntitiesConsumerGroups200ApplicationJSON struct {
	Data []GetRuntimeGroupIDCoreEntitiesConsumerGroups200ApplicationJSONData `json:"data,omitempty"`
}

type GetRuntimeGroupIDCoreEntitiesConsumerGroupsResponse struct {
	Body        []byte
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Example response
	GetRuntimeGroupIDCoreEntitiesConsumerGroups200ApplicationJSONObject *GetRuntimeGroupIDCoreEntitiesConsumerGroups200ApplicationJSON
}
