// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type ListCertificateRequest struct {
	// Offset from which to return the next set of resources. Use the value of the 'offset' field from the response of a list operation as input here to paginate through all the resources
	Offset *string `queryParam:"style=form,explode=true,name=offset"`
	// The ID of your runtime group. This variable is available in the Konnect manager
	RuntimeGroupID string `pathParam:"style=simple,explode=false,name=runtimeGroupId"`
	// Number of resources to be returned.
	Size *int64 `queryParam:"style=form,explode=true,name=size"`
	// A list of tags to filter the list of resources on. Multiple tags can be concatenated using ',' to mean AND or using '/' to mean OR.
	Tags *string `queryParam:"style=form,explode=true,name=tags"`
}

// ListCertificate200ApplicationJSONDataMetadata - metadata obtained from the certificate
type ListCertificate200ApplicationJSONDataMetadata struct {
	// The expiration date of the certificate
	Expiry *string `json:"expiry,omitempty"`
	// Information about the certificate issuer
	Issuer *string `json:"issuer,omitempty"`
	// Key usage flags for the certificate
	KeyUsages []string `json:"key_usages,omitempty"`
	// Information about the certificate
	Subject *string `json:"subject,omitempty"`
}

type ListCertificate200ApplicationJSONData struct {
	// PEM-encoded public certificate chain of the SSL key This field is referenceable and can be stored in a vault
	Cert *string `json:"cert,omitempty"`
	// Unix epoch when the resource was created
	CreatedAt *int64 `json:"created_at,omitempty"`
	// The UUID representation of the certificate object.
	ID *string `json:"id,omitempty"`
	// PEM-encoded private key of the SSL key pair. This field is _referenceable_, which means it can be securely stored as a [secret](/gateway/latest/plan-and-deploy/security/secrets-management/getting-started) in a vault. References must follow a [specific format](/gateway/latest/plan-and-deploy/security/secrets-management/reference-format).
	Key *string `json:"key,omitempty"`
	// metadata obtained from the certificate
	Metadata *ListCertificate200ApplicationJSONDataMetadata `json:"metadata,omitempty"`
	// An optional set of strings associated with the Certificate for grouping and filtering
	Tags []string `json:"tags,omitempty"`
	// Unix epoch when the resource was updated
	UpdatedAt *int64 `json:"updated_at,omitempty"`
}

// ListCertificate200ApplicationJSON - A certificate object represents a public certificate. These fields are _referenceable_.
type ListCertificate200ApplicationJSON struct {
	// An array containing certificate information.
	Data []ListCertificate200ApplicationJSONData `json:"data,omitempty"`
}

type ListCertificateResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// A certificate object represents a public certificate. These fields are _referenceable_.
	ListCertificate200ApplicationJSONObject *ListCertificate200ApplicationJSON
}
