// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"Konnect/internal/sdk/pkg/models/shared"
	"net/http"
)

type PatchPortalTeamGroupMappingsRequestBodyData struct {
	Groups []string `json:"groups,omitempty"`
	TeamID *string  `json:"team_id,omitempty"`
}

type PatchPortalTeamGroupMappingsRequestBody struct {
	// The IdP groups to map to the given team.
	Data []PatchPortalTeamGroupMappingsRequestBodyData `json:"data,omitempty"`
}

type PatchPortalTeamGroupMappingsRequest struct {
	RequestBody *PatchPortalTeamGroupMappingsRequestBody `request:"mediaType=application/json"`
	// ID of the portal.
	PortalID string `pathParam:"style=simple,explode=false,name=portalId"`
}

// PatchPortalTeamGroupMappings200ApplicationJSON - A paginated collection of mappings grouped by team_id.
type PatchPortalTeamGroupMappings200ApplicationJSON struct {
	Data []shared.PortalTeamGroupMapping `json:"data,omitempty"`
	// returns the pagination information
	Meta *shared.PaginatedMeta `json:"meta,omitempty"`
}

type PatchPortalTeamGroupMappingsResponse struct {
	// Bad Request
	BadRequestError *shared.BadRequestError
	ContentType     string
	// Forbidden
	ForbiddenError *shared.ForbiddenError
	StatusCode     int
	RawResponse    *http.Response
	// Unauthorized
	UnauthorizedError *shared.UnauthorizedError
	// A paginated collection of mappings grouped by team_id.
	PatchPortalTeamGroupMappings200ApplicationJSONObject *PatchPortalTeamGroupMappings200ApplicationJSON
}
