// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"Konnect/internal/sdk/pkg/models/shared"
	"net/http"
)

type PatchTeamGroupMappingsRequestBodyData struct {
	Groups []string `json:"groups,omitempty"`
	TeamID *string  `json:"team_id,omitempty"`
}

// PatchTeamGroupMappingsRequestBody - The request schema for a partial update of mappings from Konnect Teams to IdP Groups.
type PatchTeamGroupMappingsRequestBody struct {
	// The IdP groups to map to the given team.
	Data []PatchTeamGroupMappingsRequestBodyData `json:"data,omitempty"`
}

// PatchTeamGroupMappings200ApplicationJSON - A paginated collection of mappings grouped by team_id.
type PatchTeamGroupMappings200ApplicationJSON struct {
	Data []shared.TeamGroupMapping `json:"data,omitempty"`
	// returns the pagination information
	Meta *shared.PaginatedMeta `json:"meta,omitempty"`
}

type PatchTeamGroupMappingsResponse struct {
	// Bad Request
	BadRequestError *shared.BadRequestError
	ContentType     string
	// Permission denied
	ForbiddenError *shared.ForbiddenError
	StatusCode     int
	RawResponse    *http.Response
	// Unauthenticated
	UnauthorizedError *shared.UnauthorizedError
	// A paginated collection of mappings grouped by team_id.
	PatchTeamGroupMappings200ApplicationJSONObject *PatchTeamGroupMappings200ApplicationJSON
}
