// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"konnect/internal/sdk/pkg/models/shared"
	"net/http"
)

type PostRuntimeGroupsIDCompositeMembershipsRemoveRequestBodyMembers struct {
	ID *string `json:"id,omitempty"`
}

// PostRuntimeGroupsIDCompositeMembershipsRemoveRequestBody - Request body for removing a list of child runtime groups from a composite runtime group membership.
type PostRuntimeGroupsIDCompositeMembershipsRemoveRequestBody struct {
	Members []PostRuntimeGroupsIDCompositeMembershipsRemoveRequestBodyMembers `json:"members,omitempty"`
}

type PostRuntimeGroupsIDCompositeMembershipsRemoveRequest struct {
	// Request body for removing a list of child runtime groups from a composite runtime group membership.
	RequestBody *PostRuntimeGroupsIDCompositeMembershipsRemoveRequestBody `request:"mediaType=application/json"`
	// ID of a composite runtime group
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

// PostRuntimeGroupsIDCompositeMembershipsRemoveServiceUnavailableErrorStatus - The HTTP status code.
type PostRuntimeGroupsIDCompositeMembershipsRemoveServiceUnavailableErrorStatus int64

const (
	PostRuntimeGroupsIDCompositeMembershipsRemoveServiceUnavailableErrorStatusFiveHundredAndThree PostRuntimeGroupsIDCompositeMembershipsRemoveServiceUnavailableErrorStatus = 503
)

func (e PostRuntimeGroupsIDCompositeMembershipsRemoveServiceUnavailableErrorStatus) ToPointer() *PostRuntimeGroupsIDCompositeMembershipsRemoveServiceUnavailableErrorStatus {
	return &e
}

func (e *PostRuntimeGroupsIDCompositeMembershipsRemoveServiceUnavailableErrorStatus) UnmarshalJSON(data []byte) error {
	var v int64
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case 503:
		*e = PostRuntimeGroupsIDCompositeMembershipsRemoveServiceUnavailableErrorStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PostRuntimeGroupsIDCompositeMembershipsRemoveServiceUnavailableErrorStatus: %v", v)
	}
}

// PostRuntimeGroupsIDCompositeMembershipsRemoveServiceUnavailableError - Error response for temporary service unavailability.
type PostRuntimeGroupsIDCompositeMembershipsRemoveServiceUnavailableError struct {
	// Details about the error.
	Detail *string `json:"detail,omitempty"`
	// The Konnect traceback code
	Instance string `json:"instance"`
	// The HTTP status code.
	Status PostRuntimeGroupsIDCompositeMembershipsRemoveServiceUnavailableErrorStatus `json:"status"`
	// The error response code.
	Title string `json:"title"`
}

type PostRuntimeGroupsIDCompositeMembershipsRemoveResponse struct {
	// Bad Request
	BadRequestError *shared.BadRequestError
	ContentType     string
	// Forbidden
	ForbiddenError *shared.ForbiddenError
	// Not Found
	NotFoundError *shared.NotFoundError
	StatusCode    int
	RawResponse   *http.Response
	// Service Unavailable
	ServiceUnavailableError *PostRuntimeGroupsIDCompositeMembershipsRemoveServiceUnavailableError
	// Unauthorized
	UnauthorizedError *shared.UnauthorizedError
}
