// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/kong/terraform-provider-konnect/internal/sdk/pkg/models/shared"
	"net/http"
)

type PostControlPlanesControlPlaneIDCoreEntitiesConsumersConsumerIDBasicAuthRequest struct {
	// ID of the Consumer to lookup
	ConsumerID string `pathParam:"style=simple,explode=false,name=ConsumerId"`
	// Description of new Basic-auth credential for creation
	CreateBasicAuthWithoutParents shared.CreateBasicAuthWithoutParents `request:"mediaType=application/json"`
	// The UUID of your control plane. This variable is available in the Konnect manager.
	ControlPlaneID string `pathParam:"style=simple,explode=false,name=controlPlaneId"`
}

func (o *PostControlPlanesControlPlaneIDCoreEntitiesConsumersConsumerIDBasicAuthRequest) GetConsumerID() string {
	if o == nil {
		return ""
	}
	return o.ConsumerID
}

func (o *PostControlPlanesControlPlaneIDCoreEntitiesConsumersConsumerIDBasicAuthRequest) GetCreateBasicAuthWithoutParents() shared.CreateBasicAuthWithoutParents {
	if o == nil {
		return shared.CreateBasicAuthWithoutParents{}
	}
	return o.CreateBasicAuthWithoutParents
}

func (o *PostControlPlanesControlPlaneIDCoreEntitiesConsumersConsumerIDBasicAuthRequest) GetControlPlaneID() string {
	if o == nil {
		return ""
	}
	return o.ControlPlaneID
}

// PostControlPlanesControlPlaneIDCoreEntitiesConsumersConsumerIDBasicAuthResponseBody - Invalid Basic-auth credential
type PostControlPlanesControlPlaneIDCoreEntitiesConsumersConsumerIDBasicAuthResponseBody struct {
}

type PostControlPlanesControlPlaneIDCoreEntitiesConsumersConsumerIDBasicAuthResponse struct {
	// Successfully created Basic-auth credential
	BasicAuth *shared.BasicAuth
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Invalid Basic-auth credential
	Object *PostControlPlanesControlPlaneIDCoreEntitiesConsumersConsumerIDBasicAuthResponseBody
}

func (o *PostControlPlanesControlPlaneIDCoreEntitiesConsumersConsumerIDBasicAuthResponse) GetBasicAuth() *shared.BasicAuth {
	if o == nil {
		return nil
	}
	return o.BasicAuth
}

func (o *PostControlPlanesControlPlaneIDCoreEntitiesConsumersConsumerIDBasicAuthResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *PostControlPlanesControlPlaneIDCoreEntitiesConsumersConsumerIDBasicAuthResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *PostControlPlanesControlPlaneIDCoreEntitiesConsumersConsumerIDBasicAuthResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *PostControlPlanesControlPlaneIDCoreEntitiesConsumersConsumerIDBasicAuthResponse) GetObject() *PostControlPlanesControlPlaneIDCoreEntitiesConsumersConsumerIDBasicAuthResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
