// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

// PutRuntimeGroupIDCoreEntitiesConsumerGroupsGroupIDRequestBody - Consumer request body
type PutRuntimeGroupIDCoreEntitiesConsumerGroupsGroupIDRequestBody struct {
	// Field for storing an existing unique ID for the Consumer - useful for mapping Kong with users in your existing database. You must send either this field or username with the request.
	//
	CustomID string `json:"custom_id"`
	// An optional set of strings associated with the Consumer for grouping and filtering.
	//
	Tags []string `json:"tags,omitempty"`
	// The unique username of the Consumer. You must send either this field or custom_id with the request.
	//
	Username string `json:"username"`
}

type PutRuntimeGroupIDCoreEntitiesConsumerGroupsGroupIDRequest struct {
	// Consumer request body
	RequestBody *PutRuntimeGroupIDCoreEntitiesConsumerGroupsGroupIDRequestBody `request:"mediaType=application/json"`
	// The UUID of the consumer group.
	GroupID string `pathParam:"style=simple,explode=false,name=group_id"`
	// The ID of your runtime group. This variable is available in the Konnect manager
	RuntimeGroupID string `pathParam:"style=simple,explode=false,name=runtimeGroupId"`
}

type PutRuntimeGroupIDCoreEntitiesConsumerGroupsGroupID200ApplicationJSONData struct {
	// Unix epoch when the resource was created.
	CreatedAt *int64 `json:"created_at,omitempty"`
	// Field for storing an existing unique ID for the Consumer - useful for mapping Kong with users in your existing database.
	CustomID *string `json:"custom_id,omitempty"`
	// The unique identifier or the name attribute of the consumer.
	ID *string `json:"id,omitempty"`
	// An optional set of strings associated with the Consumer for grouping and filtering.
	//
	Tags []string `json:"tags,omitempty"`
	// Unix epoch when the resource was created.
	UpdatedAt *string `json:"updated_at,omitempty"`
	// The unique username of the consumer. You must send either this field or` custom_i`d with the request.
	Username *string `json:"username,omitempty"`
}

// PutRuntimeGroupIDCoreEntitiesConsumerGroupsGroupID200ApplicationJSON - The consumer object response body
type PutRuntimeGroupIDCoreEntitiesConsumerGroupsGroupID200ApplicationJSON struct {
	Data []PutRuntimeGroupIDCoreEntitiesConsumerGroupsGroupID200ApplicationJSONData `json:"data,omitempty"`
	// Pagination information
	Next *string `json:"next,omitempty"`
}

type PutRuntimeGroupIDCoreEntitiesConsumerGroupsGroupIDResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// The consumer object response body
	PutRuntimeGroupIDCoreEntitiesConsumerGroupsGroupID200ApplicationJSONObject *PutRuntimeGroupIDCoreEntitiesConsumerGroupsGroupID200ApplicationJSON
}
