// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"Konnect/internal/sdk/pkg/models/shared"
	"net/http"
)

// UpdateTeamRequestBody - The request schema for the update team request.
type UpdateTeamRequestBody struct {
	// The description of the team.
	Description *string `json:"description,omitempty"`
	// The name of the team.
	Name *string `json:"name,omitempty"`
}

type UpdateTeamRequest struct {
	// The request schema for the update team request.
	RequestBody *UpdateTeamRequestBody `request:"mediaType=application/json"`
	// The team ID
	TeamID string `pathParam:"style=simple,explode=false,name=teamId"`
}

type UpdateTeamResponse struct {
	// Bad Request
	BadRequestError *shared.BadRequestError
	ContentType     string
	// Not Found
	NotFoundError *shared.NotFoundError
	StatusCode    int
	RawResponse   *http.Response
	// A response including a single team.
	Team *shared.Team
}
