// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"Konnect/internal/sdk/pkg/models/shared"
	"net/http"
)

type UpdateIdpTeamMappingsRequestBodyMappings struct {
	Group   *string  `json:"group,omitempty"`
	TeamIds []string `json:"team_ids,omitempty"`
}

// UpdateIdpTeamMappingsRequestBody - The request schema for updating IdP team mappings.
type UpdateIdpTeamMappingsRequestBody struct {
	// The mappings object.
	Mappings []UpdateIdpTeamMappingsRequestBodyMappings `json:"mappings,omitempty"`
}

// UpdateIdpTeamMappings412ApplicationProblemPlusJSON - The error response object.
type UpdateIdpTeamMappings412ApplicationProblemPlusJSON struct {
	// Details about the error response.
	Detail *string `json:"detail,omitempty"`
	// The Konnect traceback code.
	Instance *string `json:"instance,omitempty"`
	// The HTTP status code.
	Status *int64 `json:"status,omitempty"`
	// The error response code.
	Title *string `json:"title,omitempty"`
}

// UpdateIdpTeamMappings200ApplicationJSON - A paginated list response for a collection of team mappings.
type UpdateIdpTeamMappings200ApplicationJSON struct {
	Data []shared.TeamMapping `json:"data,omitempty"`
}

type UpdateIdpTeamMappingsResponse struct {
	// Bad Request
	BadRequestError *shared.BadRequestError
	ContentType     string
	// Permission denied
	ForbiddenError *shared.ForbiddenError
	// Not Found
	NotFoundError *shared.NotFoundError
	StatusCode    int
	RawResponse   *http.Response
	// A paginated list response for a collection of team mappings.
	UpdateIdpTeamMappings200ApplicationJSONObject *UpdateIdpTeamMappings200ApplicationJSON
	// Precondition Failed
	UpdateIdpTeamMappings412ApplicationProblemPlusJSONObject *UpdateIdpTeamMappings412ApplicationProblemPlusJSON
}
