// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/kong/terraform-provider-konnect/internal/sdk/pkg/models/shared"
	"net/http"
)

type UpdateExittransformerPluginRequest struct {
	// Description of the Plugin
	CreateExitTransformerPlugin shared.CreateExitTransformerPlugin `request:"mediaType=application/json"`
	// ID of the Plugin to lookup
	PluginID string `pathParam:"style=simple,explode=false,name=PluginId"`
	// The UUID of your control plane. This variable is available in the Konnect manager.
	ControlPlaneID string `pathParam:"style=simple,explode=false,name=controlPlaneId"`
}

func (o *UpdateExittransformerPluginRequest) GetCreateExitTransformerPlugin() shared.CreateExitTransformerPlugin {
	if o == nil {
		return shared.CreateExitTransformerPlugin{}
	}
	return o.CreateExitTransformerPlugin
}

func (o *UpdateExittransformerPluginRequest) GetPluginID() string {
	if o == nil {
		return ""
	}
	return o.PluginID
}

func (o *UpdateExittransformerPluginRequest) GetControlPlaneID() string {
	if o == nil {
		return ""
	}
	return o.ControlPlaneID
}

// UpdateExittransformerPluginResponseBody - Invalid Plugin
type UpdateExittransformerPluginResponseBody struct {
}

type UpdateExittransformerPluginResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Successfully upserted Plugin
	ExitTransformerPlugin *shared.ExitTransformerPlugin
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Unauthorized
	UnauthorizedError *shared.UnauthorizedError
	// Invalid Plugin
	Object *UpdateExittransformerPluginResponseBody
}

func (o *UpdateExittransformerPluginResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *UpdateExittransformerPluginResponse) GetExitTransformerPlugin() *shared.ExitTransformerPlugin {
	if o == nil {
		return nil
	}
	return o.ExitTransformerPlugin
}

func (o *UpdateExittransformerPluginResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *UpdateExittransformerPluginResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *UpdateExittransformerPluginResponse) GetUnauthorizedError() *shared.UnauthorizedError {
	if o == nil {
		return nil
	}
	return o.UnauthorizedError
}

func (o *UpdateExittransformerPluginResponse) GetObject() *UpdateExittransformerPluginResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
