// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/kong/terraform-provider-konnect/internal/sdk/pkg/models/shared"
	"net/http"
)

type UpdateAPIProductVersionRequest struct {
	UpdateAPIProductVersionDTO shared.UpdateAPIProductVersionDTO `request:"mediaType=application/json"`
	// The API product identifier
	APIProductID string `pathParam:"style=simple,explode=false,name=apiProductId"`
	// The API product version identifier
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *UpdateAPIProductVersionRequest) GetUpdateAPIProductVersionDTO() shared.UpdateAPIProductVersionDTO {
	if o == nil {
		return shared.UpdateAPIProductVersionDTO{}
	}
	return o.UpdateAPIProductVersionDTO
}

func (o *UpdateAPIProductVersionRequest) GetAPIProductID() string {
	if o == nil {
		return ""
	}
	return o.APIProductID
}

func (o *UpdateAPIProductVersionRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

type UpdateAPIProductVersionResponse struct {
	// API product
	APIProductVersion *shared.APIProductVersion
	// Bad Request
	BadRequestError *shared.BadRequestError
	// HTTP response content type for this operation
	ContentType string
	// Forbidden
	ForbiddenError *shared.ForbiddenError
	// Not Found
	NotFoundError *shared.NotFoundError
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Unauthorized
	UnauthorizedError *shared.UnauthorizedError
	// Unsupported Media Type
	UnsupportedMediaTypeError *shared.UnsupportedMediaTypeError
}

func (o *UpdateAPIProductVersionResponse) GetAPIProductVersion() *shared.APIProductVersion {
	if o == nil {
		return nil
	}
	return o.APIProductVersion
}

func (o *UpdateAPIProductVersionResponse) GetBadRequestError() *shared.BadRequestError {
	if o == nil {
		return nil
	}
	return o.BadRequestError
}

func (o *UpdateAPIProductVersionResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *UpdateAPIProductVersionResponse) GetForbiddenError() *shared.ForbiddenError {
	if o == nil {
		return nil
	}
	return o.ForbiddenError
}

func (o *UpdateAPIProductVersionResponse) GetNotFoundError() *shared.NotFoundError {
	if o == nil {
		return nil
	}
	return o.NotFoundError
}

func (o *UpdateAPIProductVersionResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *UpdateAPIProductVersionResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *UpdateAPIProductVersionResponse) GetUnauthorizedError() *shared.UnauthorizedError {
	if o == nil {
		return nil
	}
	return o.UnauthorizedError
}

func (o *UpdateAPIProductVersionResponse) GetUnsupportedMediaTypeError() *shared.UnsupportedMediaTypeError {
	if o == nil {
		return nil
	}
	return o.UnsupportedMediaTypeError
}
