// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"Konnect/internal/sdk/pkg/models/shared"
	"net/http"
)

type UpdateAPIProductRequest struct {
	UpdateAPIProductDTO shared.UpdateAPIProductDTO `request:"mediaType=application/json"`
	// API product identifier
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

type UpdateAPIProductResponse struct {
	// API product
	APIProduct *shared.APIProduct
	// Bad Request
	BadRequestError *shared.BadRequestError
	ContentType     string
	// Forbidden
	ForbiddenError *shared.ForbiddenError
	// Not Found
	NotFoundError *shared.NotFoundError
	StatusCode    int
	RawResponse   *http.Response
	// Unauthorized
	UnauthorizedError *shared.UnauthorizedError
	// Unsupported Media Type
	UnsupportedMediaTypeError *shared.UnsupportedMediaTypeError
}
