// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"Konnect/internal/sdk/pkg/models/shared"
	"encoding/json"
	"fmt"
	"net/http"
)

type UpdateRuntimeGroupRequest struct {
	UpdateRuntimeGroupRequest shared.UpdateRuntimeGroupRequest `request:"mediaType=application/json"`
	// The runtime group ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

// UpdateRuntimeGroupServiceUnavailableErrorStatus - The HTTP status code.
type UpdateRuntimeGroupServiceUnavailableErrorStatus int64

const (
	UpdateRuntimeGroupServiceUnavailableErrorStatusFiveHundredAndThree UpdateRuntimeGroupServiceUnavailableErrorStatus = 503
)

func (e UpdateRuntimeGroupServiceUnavailableErrorStatus) ToPointer() *UpdateRuntimeGroupServiceUnavailableErrorStatus {
	return &e
}

func (e *UpdateRuntimeGroupServiceUnavailableErrorStatus) UnmarshalJSON(data []byte) error {
	var v int64
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case 503:
		*e = UpdateRuntimeGroupServiceUnavailableErrorStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for UpdateRuntimeGroupServiceUnavailableErrorStatus: %v", v)
	}
}

// UpdateRuntimeGroupServiceUnavailableError - Error response for temporary service unavailability.
type UpdateRuntimeGroupServiceUnavailableError struct {
	// Details about the error.
	Detail *string `json:"detail,omitempty"`
	// The Konnect traceback code
	Instance string `json:"instance"`
	// The HTTP status code.
	Status UpdateRuntimeGroupServiceUnavailableErrorStatus `json:"status"`
	// The error response code.
	Title string `json:"title"`
}

// UpdateRuntimeGroupInternalServerErrorStatus - The HTTP status code.
type UpdateRuntimeGroupInternalServerErrorStatus int64

const (
	UpdateRuntimeGroupInternalServerErrorStatusFiveHundred UpdateRuntimeGroupInternalServerErrorStatus = 500
)

func (e UpdateRuntimeGroupInternalServerErrorStatus) ToPointer() *UpdateRuntimeGroupInternalServerErrorStatus {
	return &e
}

func (e *UpdateRuntimeGroupInternalServerErrorStatus) UnmarshalJSON(data []byte) error {
	var v int64
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case 500:
		*e = UpdateRuntimeGroupInternalServerErrorStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for UpdateRuntimeGroupInternalServerErrorStatus: %v", v)
	}
}

// UpdateRuntimeGroupInternalServerError - The error response object.
type UpdateRuntimeGroupInternalServerError struct {
	// Details about the error.
	Detail *string `json:"detail,omitempty"`
	// The Konnect traceback code
	Instance string `json:"instance"`
	// The HTTP status code.
	Status UpdateRuntimeGroupInternalServerErrorStatus `json:"status"`
	// The error response code.
	Title string `json:"title"`
}

type UpdateRuntimeGroupResponse struct {
	// Bad Request
	BadRequestError *shared.BadRequestError
	ContentType     string
	// Permission denied
	ForbiddenError *shared.ForbiddenError
	// Internal Server Error
	InternalServerError *UpdateRuntimeGroupInternalServerError
	// Not Found
	NotFoundError *shared.NotFoundError
	// A response to updating a runtime group.
	RuntimeGroup *shared.RuntimeGroup
	StatusCode   int
	RawResponse  *http.Response
	// Service Unavailable
	ServiceUnavailableError *UpdateRuntimeGroupServiceUnavailableError
	// Unauthenticated
	UnauthorizedError *shared.UnauthorizedError
}
