// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"net/http"
)

// UpsertPluginForAServiceRequestBodyConfig - The configuration properties for the Plugin
type UpsertPluginForAServiceRequestBodyConfig struct {
	Hour   *int64 `json:"hour,omitempty"`
	Minute *int64 `json:"minute,omitempty"`
}

type UpsertPluginForAServiceRequestBodyProtocols string

const (
	UpsertPluginForAServiceRequestBodyProtocolsHTTP  UpsertPluginForAServiceRequestBodyProtocols = "http"
	UpsertPluginForAServiceRequestBodyProtocolsGrpc  UpsertPluginForAServiceRequestBodyProtocols = "grpc"
	UpsertPluginForAServiceRequestBodyProtocolsGrpcs UpsertPluginForAServiceRequestBodyProtocols = "grpcs"
	UpsertPluginForAServiceRequestBodyProtocolsTLS   UpsertPluginForAServiceRequestBodyProtocols = "tls"
	UpsertPluginForAServiceRequestBodyProtocolsTCP   UpsertPluginForAServiceRequestBodyProtocols = "tcp"
)

func (e UpsertPluginForAServiceRequestBodyProtocols) ToPointer() *UpsertPluginForAServiceRequestBodyProtocols {
	return &e
}

func (e *UpsertPluginForAServiceRequestBodyProtocols) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "http":
		fallthrough
	case "grpc":
		fallthrough
	case "grpcs":
		fallthrough
	case "tls":
		fallthrough
	case "tcp":
		*e = UpsertPluginForAServiceRequestBodyProtocols(v)
		return nil
	default:
		return fmt.Errorf("invalid value for UpsertPluginForAServiceRequestBodyProtocols: %v", v)
	}
}

// UpsertPluginForAServiceRequestBodyRoute - If set, the plugin will only activate when receiving requests via the specified route. Leave unset for the plugin to activate regardless of the route being used. Default: `null`.With form-encoded, the notation is `route.id=<route id> or route.name=<route name>`. With JSON, use `route:{id:<route id>}` or `route:{name:<route name>}`.
type UpsertPluginForAServiceRequestBodyRoute struct {
	// The Id of the route.
	ID *string `json:"id,omitempty"`
}

// UpsertPluginForAServiceRequestBodyService - If set, the plugin will only activate when receiving requests via one of the routes belonging to the specified service.
type UpsertPluginForAServiceRequestBodyService struct {
	// The Id of the route.
	ID *string `json:"id,omitempty"`
}

// UpsertPluginForAServiceRequestBody - Plugin request body
type UpsertPluginForAServiceRequestBody struct {
	// The configuration properties for the Plugin
	Config *UpsertPluginForAServiceRequestBodyConfig `json:"config,omitempty"`
	// Whether the plugin is applied. Default: `true`.
	//
	Enabled *bool `json:"enabled,omitempty"`
	// The Plugin instance name.
	//
	InstanceName *string `json:"instance_name,omitempty"`
	// The name of the Plugin that’s going to be added. Currently, the Plugin must be installed in every Kong instance separately.
	Name *string `json:"name,omitempty"`
	// A list of the request protocols that will trigger this plugin.
	Protocols []UpsertPluginForAServiceRequestBodyProtocols `json:"protocols,omitempty"`
	// If set, the plugin will only activate when receiving requests via the specified route. Leave unset for the plugin to activate regardless of the route being used. Default: `null`.With form-encoded, the notation is `route.id=<route id> or route.name=<route name>`. With JSON, use `route:{id:<route id>}` or `route:{name:<route name>}`.
	Route *UpsertPluginForAServiceRequestBodyRoute `json:"route,omitempty"`
	// If set, the plugin will only activate when receiving requests via one of the routes belonging to the specified service.
	Service *UpsertPluginForAServiceRequestBodyService `json:"service,omitempty"`
	// An optional set of strings associated with the Plugin for grouping and filtering.
	//
	Tags []string `json:"tags,omitempty"`
}

type UpsertPluginForAServiceRequest struct {
	// Plugin request body
	RequestBody *UpsertPluginForAServiceRequestBody `request:"mediaType=application/json"`
	// The unique identifier of the Plugin to create or update.
	PluginIDOrInstanceName string `pathParam:"style=simple,explode=false,name=plugin_id_or_instance_name"`
	// The ID of your runtime group. This variable is available in the Konnect manager
	RuntimeGroupID string `pathParam:"style=simple,explode=false,name=runtimeGroupId"`
	// ID **or** name of the service to lookup
	ServiceID string `pathParam:"style=simple,explode=false,name=service_id"`
}

// UpsertPluginForAService400ApplicationJSON - Invalid Plugin
type UpsertPluginForAService400ApplicationJSON struct {
}

// UpsertPluginForAService201ApplicationJSONConfig - The configuration properties for the Plugin
type UpsertPluginForAService201ApplicationJSONConfig struct {
	Hour   *int64 `json:"hour,omitempty"`
	Minute *int64 `json:"minute,omitempty"`
}

type UpsertPluginForAService201ApplicationJSONProtocols string

const (
	UpsertPluginForAService201ApplicationJSONProtocolsHTTP  UpsertPluginForAService201ApplicationJSONProtocols = "http"
	UpsertPluginForAService201ApplicationJSONProtocolsGrpc  UpsertPluginForAService201ApplicationJSONProtocols = "grpc"
	UpsertPluginForAService201ApplicationJSONProtocolsGrpcs UpsertPluginForAService201ApplicationJSONProtocols = "grpcs"
	UpsertPluginForAService201ApplicationJSONProtocolsTLS   UpsertPluginForAService201ApplicationJSONProtocols = "tls"
	UpsertPluginForAService201ApplicationJSONProtocolsTCP   UpsertPluginForAService201ApplicationJSONProtocols = "tcp"
)

func (e UpsertPluginForAService201ApplicationJSONProtocols) ToPointer() *UpsertPluginForAService201ApplicationJSONProtocols {
	return &e
}

func (e *UpsertPluginForAService201ApplicationJSONProtocols) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "http":
		fallthrough
	case "grpc":
		fallthrough
	case "grpcs":
		fallthrough
	case "tls":
		fallthrough
	case "tcp":
		*e = UpsertPluginForAService201ApplicationJSONProtocols(v)
		return nil
	default:
		return fmt.Errorf("invalid value for UpsertPluginForAService201ApplicationJSONProtocols: %v", v)
	}
}

// UpsertPluginForAService201ApplicationJSON - Example response
type UpsertPluginForAService201ApplicationJSON struct {
	// The configuration properties for the Plugin
	Config *UpsertPluginForAService201ApplicationJSONConfig `json:"config,omitempty"`
	// If set, the plugin will activate only for requests where the specified has been authenticated. (Note that some plugins can not be restricted to consumers this way.)
	Consumer *string `json:"consumer,omitempty"`
	// Unix epoch when the resource was created.
	CreatedAt *int64 `json:"created_at,omitempty"`
	// Whether the plugin is applied. Default: `true`.
	//
	Enabled *bool   `json:"enabled,omitempty"`
	ID      *string `json:"id,omitempty"`
	// The Plugin instance name.
	//
	InstanceName *string `json:"instance_name,omitempty"`
	// The name of the Plugin that’s going to be added. Currently, the Plugin must be installed in every Kong instance separately.
	Name *string `json:"name,omitempty"`
	// A list of the request protocols that will trigger this plugin.
	Protocols []UpsertPluginForAService201ApplicationJSONProtocols `json:"protocols,omitempty"`
	// If set, the plugin will only activate when receiving requests via the specified route. Leave unset for the plugin to activate regardless of the route being used. Default: `null`.With form-encoded, the notation is `route.id=<route id> or route.name=<route name>`. With JSON, use `route:{id:<route id>}` or `route:{name:<route name>}`.
	Route *string `json:"route,omitempty"`
	// If set, the plugin will only activate when receiving requests via one of the routes belonging to the specified service.
	Service *string `json:"service,omitempty"`
	// An optional set of strings associated with the Plugin for grouping and filtering.
	//
	Tags []string `json:"tags,omitempty"`
}

type UpsertPluginForAServiceResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Example response
	UpsertPluginForAService201ApplicationJSONObject *UpsertPluginForAService201ApplicationJSON
	// Invalid Plugin
	UpsertPluginForAService400ApplicationJSONObject *UpsertPluginForAService400ApplicationJSON
}
