// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"Konnect/internal/sdk/pkg/models/shared"
	"encoding/json"
	"fmt"
	"net/http"
)

// UsersAssignRoleRequestBodyEntityRegion - The region of the team.
type UsersAssignRoleRequestBodyEntityRegion string

const (
	UsersAssignRoleRequestBodyEntityRegionUs       UsersAssignRoleRequestBodyEntityRegion = "us"
	UsersAssignRoleRequestBodyEntityRegionEu       UsersAssignRoleRequestBodyEntityRegion = "eu"
	UsersAssignRoleRequestBodyEntityRegionWildcard UsersAssignRoleRequestBodyEntityRegion = "*"
)

func (e UsersAssignRoleRequestBodyEntityRegion) ToPointer() *UsersAssignRoleRequestBodyEntityRegion {
	return &e
}

func (e *UsersAssignRoleRequestBodyEntityRegion) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "us":
		fallthrough
	case "eu":
		fallthrough
	case "*":
		*e = UsersAssignRoleRequestBodyEntityRegion(v)
		return nil
	default:
		return fmt.Errorf("invalid value for UsersAssignRoleRequestBodyEntityRegion: %v", v)
	}
}

// UsersAssignRoleRequestBody - An assigned role is a role that has been assigned to a user or team.
type UsersAssignRoleRequestBody struct {
	// The ID of the entity.
	EntityID *string `json:"entity_id,omitempty"`
	// The region of the team.
	EntityRegion *UsersAssignRoleRequestBodyEntityRegion `json:"entity_region,omitempty"`
	// The type of entity.
	EntityTypeName *string `json:"entity_type_name,omitempty"`
	// The desired role.
	RoleName *string `json:"role_name,omitempty"`
}

type UsersAssignRoleRequest struct {
	// The request schema for assigning a role.
	RequestBody *UsersAssignRoleRequestBody `request:"mediaType=application/json"`
	// The user ID
	UserID string `pathParam:"style=simple,explode=false,name=userId"`
}

type UsersAssignRoleResponse struct {
	// A get action response of a single assigned role.
	AssignedRole *shared.AssignedRole
	// Bad Request
	BadRequestError *shared.BadRequestError
	// Conflict
	ConflictError *shared.ConflictError
	ContentType   string
	// Permission denied
	ForbiddenError *shared.ForbiddenError
	// Not Found
	NotFoundError *shared.NotFoundError
	StatusCode    int
	RawResponse   *http.Response
	// Unauthenticated
	UnauthorizedError *shared.UnauthorizedError
}
